version: "3"
services:
  web:
    build: "./LogIn"
    restart: always
    ports:
      - 3000:3000
    depends_on:
      - api

  api:
    build: "./expressjs"
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - postgres

  postgres:
    image: postgres:15
    restart: always
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - 5432:5432

volumes:
  postgres-data:
    driver: local